### ISSUE TITLE
Помилка при встановленні

### ISSUE THREAD

**Issue by bshumylo** [Joomla-Ukraine/JUPWA#1]
[Додав скриншот після встановлення](https://prnt.sc/jz2WiGD-0C2l)

**Comment by denysdesign** [comment]
Який архів встановлювали? Перший?

**Comment by denysdesign** [comment]
Ось спробуйте
https://github.com/Joomla-Ukraine/JUPWA/releases/download/1.2/pkg_jupwa_v1.2.zip
