### ISSUE TITLE
Text in `offline.php` is hard coded

### ISSUE THREAD

**Issue by rvalitov** [Joomla-Ukraine/JUPWA#12]
It would be useful if text in `offline.php` can be customized. Especially for websites in languages other than English and for multilingual Joomla websites.

**Comment by denysdesign** [comment]
You can override the offline page and the worker service in your template.

For example:
`/templates/my_template/html/jupwa/offline.php`
`/templates/my_template/html/jupwa/sw.php`

The original code is placed in:
`/plugins/system/jupwa/tmpl/offline.php`
`/plugins/system/jupwa/tmpl/sw.php`

https://github.com/Joomla-Ukraine/JUPWA/tree/main/packages/plg_system_jupwa/tmpl
