### ISSUE TITLE
Error Article Joomla

### ISSUE THREAD

**Issue by isidoroi** [Joomla-Ukraine/JUPWA#13]
I encounter this error by accessing the link of some articles on the site. Jupwa update 1.4
Joomla 4.3.2

0 JUPWA\Helpers\Images::joomlaImage(): Return value must be of type string, null returned

**Comment by denysdesign** [comment]
@isidoroi Please update to v1.5: https://github.com/Joomla-Ukraine/JUPWA/releases/tag/1.5
