### ISSUE TITLE
Problem with Component Jevents

### ISSUE THREAD

**Issue by iltuoconsulenteit** [Joomla-Ukraine/JUPWA#16]
After installing the Jevents component and creating a menu with a Calendar view, I encountered the following error: JUPWA\Helpers\HTML::text(): Argument #1 ($text) must be of type string, null given, called in /web/htdocs /www.domain.it/home/plugins/jupwa/content/content.php on line 180

Version 1.16

**Comment by denysdesign** [comment]
Hi! Please test v1.17!
