### ISSUE TITLE
Joomla 5?

### ISSUE THREAD

**Issue by iltuoconsulenteit** [Joomla-Ukraine/JUPWA#17]
Would the plugin also work on Joonla 5?

**Comment by iltuoconsulenteit** [comment]
I am testing Local Joomla 5 installation and I tried to install plugins and after enabling them I encounter these errors (xampp on windows php 8.2.12 - server: 10.4.32-MariaDB): Deprecated
: Creation of dynamic property plgSystemJUPWA::$plg is deprecated in
%path%\htdocs\plugins\system\jupwa\jupwa.php
online
69


Deprecated
: Creation of dynamic property plgSystemJUPWA::$view is deprecated in
%path%\htdocs\plugins\system\jupwa\jupwa.php
online
70


Deprecated
: Creation of dynamic property plgSystemJUPWA::$layout is deprecated in
%path%\htdocs\plugins\system\jupwa\jupwa.php
online
71


Deprecated
: Creation of dynamic property plgSystemJUPWA::$option is deprecated in
%path%\htdocs\plugins\system\jupwa\jupwa.php
online
72

**Comment by denysdesign** [comment]
You can disable warnings in Joomla settings.

In the next versions, outdated classes will be replaced with the ones that are relevant for Joomla 5

**Comment by iltuoconsulenteit** [comment]
ok, errors are no longer visible, but on Joomla 5 I always encounter this error when selecting an article in the menu: 0 JUPWA\Utils\Util::get_thumbs(): Return value must be of type string, stdClass returned

**Comment by denysdesign** [comment]
Please update and check new release!

**Comment by iltuoconsulenteit** [comment]
I updated with 1.28 and reactivated the Joomla default error management and in the backend I encounter the same Deprecated errors
: Creation of dynamic property plgSystemJUPWA::$plg is deprecated in
C:\xxx\xampp\htdocs\plugins\system\jupwa\jupwa.php
online
69


Deprecated
: Creation of dynamic property plgSystemJUPWA::$view is deprecated in
C:\xxx\xampp\htdocs\plugins\system\jupwa\jupwa.php
online
70


Deprecated
: Creation of dynamic property plgSystemJUPWA::$layout is deprecated in
C:\xxx\xampp\htdocs\plugins\system\jupwa\jupwa.php
online
71


Deprecated
: Creation of dynamic property plgSystemJUPWA::$option is deprecated in
C:\xxx\xampp\htdocs\plugins\system\jupwa\jupwa.php
online
72

**Comment by denysdesign** [comment]
Please test version 2.0.0.
Thank you 👍

**Comment by iltuoconsulenteit** [comment]
Updated to version 2.0.2 and still get the following errors:
Deprecated
: Creation of dynamic property plgSystemJUPWA::$app is deprecated in
C:\AssAgenziA\a_htdocs\AssAgenziA\plugins\system\jupwa\jupwa.php
online
58
Deprecated: Creation of dynamic property PlgJUPWAContent::$app is deprecated in C:\AssAgenziA\a_htdocs\AssAgenziA\plugins\jupwa\content\content.php on line 37

I'm also having problems where the links from the Joomla menus aren't working correctly and I need to understand if it's due to previous Jupwa installations

**Comment by iltuoconsulenteit** [comment]
Uninstalling and reinstalling I get these errors:

Deprecated
: Creation of dynamic property plgSystemJUPWA::$app is deprecated in
\plugins\system\jupwa\jupwa.php
online
58


Deprecated
: Creation of dynamic property plgSystemJUPWA::$plg is deprecated in
\plugins\system\jupwa\jupwa.php
online
65


Deprecated
: Creation of dynamic property plgSystemJUPWA::$view is deprecated in
\plugins\system\jupwa\jupwa.php
online
66


Deprecated
: Creation of dynamic property plgSystemJUPWA::$layout is deprecated in
\plugins\system\jupwa\jupwa.php
online
67


Deprecated
: Creation of dynamic property plgSystemJUPWA::$option is deprecated in
\plugins\system\jupwa\jupwa.php
online
68

**Comment by denysdesign** [comment]
> Uninstalling and reinstalling I get these errors:
> 
> Deprecated : Creation of dynamic property plgSystemJUPWA::$app is deprecated in \plugins\system\jupwa\jupwa.php online 58
> 
> Deprecated : Creation of dynamic property plgSystemJUPWA::$plg is deprecated in \plugins\system\jupwa\jupwa.php online 65
> 
> Deprecated : Creation of dynamic property plgSystemJUPWA::$view is deprecated in \plugins\system\jupwa\jupwa.php online 66
> 
> Deprecated : Creation of dynamic property plgSystemJUPWA::$layout is deprecated in \plugins\system\jupwa\jupwa.php online 67
> 
> Deprecated : Creation of dynamic property plgSystemJUPWA::$option is deprecated in \plugins\system\jupwa\jupwa.php online 68

Please test it:
https://github.com/Joomla-Ukraine/JUPWA/releases/tag/2.1.1
