### ISSUE TITLE
ImageMagick module not available with this PHP installation

### ISSUE THREAD

**Issue by bshumylo** [Joomla-Ukraine/JUPWA#2]
Після ввімкнення у "Icons" [цієї опції](https://prnt.sc/t0-QBYLHgsWb) при збереженні видає [помилку](https://prnt.sc/TxIh1nNNuwKa)
PHP 8.1.17

**Comment by denysdesign** [comment]
Додам опцію без ImageMagick. Дякую!

**Comment by bshumylo** [comment]
> @bshumylo у вас, до речі, хостинг чи сервер?

Хостинг

**Comment by denysdesign** [comment]
@bshumylo додав можливість генерації іконок без ImageMagick.

Будь ласка, оновіть плагін до версії 1.3!

**Comment by denysdesign** [comment]
Все працює?
