### ISSUE TITLE
Author field in manifest file should point to Denys Nosov?

### ISSUE THREAD

**Issue by rvalitov** [Joomla-Ukraine/JUPWA#8]
Hi! Thank you for this project. I checked the manifest file that your plugin generates and see the following `author` section in it:
```json
"author": {
        "name": "Denys Nosov",
        "website": "https://joomla-ua.org",
        "github": "https://github.com/Joomla-Ukraine/JUPWA"
    }
```

I understand your authorship and credit notes, that's perfectly fine to have them somewhere in code. But I've always been thinking that information in the manifest file describes only the PWA itself, i.e. putting their your authorship can lead to misunderstanding that the whole PWA is developed by you which is not true. Do you think it's OK to remove this block from the manifest file?

**Comment by denysdesign** [comment]
I'm tested all manifest params.

**Comment by rvalitov** [comment]
That's great you testing it! However it still does not resolve the question I posed.

**Comment by denysdesign** [comment]
So remove strings
